application:
  id: 1
  persistence:
    oracle:
      name: oracle-datasource
      url: \${oracle.db.url?:UNDEFINED}
      username: \${oracle.username?:UNDEFINED}
      password: \${oracle.password?:UNDEFINED}
      schema: \${oracle.schema?:UNDEFINED}
      driver: oracle.jdbc.OracleDriver

info:
  app:
    name: ${rootProject.name}
    description: ${project.description}
    version: ${project.version}
    distributed-id: \${application.id}

spring:
  main:
    lazy-initialization: true
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    hikari:
      pool-name: \${application.persistence.oracle.name}-hikari-pool
      jdbc-url:  \${application.persistence.oracle.url}
      username:  \${application.persistence.oracle.username}
      password:  \${application.persistence.oracle.password}
      driver-class-name: \${application.persistence.oracle.driver}
      schema: \${application.persistence.oracle.schema}
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 1
      idle-timeout: 1
      max-lifetime: 1

