application:
  id: 1
  persistence:
    oracle:
      name: oracle-datasource
      url: \${oracle.db.url?:UNDEFINED}
      username: \${oracle.username?:UNDEFINED}
      password: \${oracle.password?:UNDEFINED}
      schema: \${oracle.schema?:UNDEFINED}
      dialect: org.hibernate.dialect.Oracle12cDialect
      driver: oracle.jdbc.OracleDriver

info:
  app:
    name: ${rootProject.name}
    description: ${project.description}
    version: ${project.version}
    distributed-id: \${application.id}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
